// Cuanto se usa cada contenido en italiano REAL hablado. Sirve para que el
// alumno sepa donde apretar: no vale lo mismo el passato prossimo (cada dia)
// que la nominalizacion (un informe). Clave -> [categoria, explicacion].
const USO_REAL = {
    "M1-L1": ["diario", "Lo vas a usar cada día al hablar"],
    "M1-L2": ["diario", "Lo vas a usar cada día al hablar"],
    "M1-L3": ["diario", "Lo vas a usar cada día al hablar"],
    "M1-L4": ["diario", "Lo vas a usar cada día al hablar"],
    "M1-L5": ["diario", "Lo vas a usar cada día al hablar"],
    "M1-L6": ["diario", "Lo vas a usar cada día al hablar"],
    "M1-L7": ["diario", "Lo vas a usar cada día al hablar"],
    "M1-L8": ["diario", "Lo vas a usar cada día al hablar"],
    "M1-L9": ["diario", "Lo vas a usar cada día al hablar"],
    "M1-L10": ["diario", "Lo vas a usar cada día al hablar"],
    "M2-L1": ["diario", "Lo vas a usar cada día al hablar"],
    "M2-L2": ["diario", "Lo vas a usar cada día al hablar"],
    "M2-L3": ["diario", "Lo vas a usar cada día al hablar"],
    "M2-L4": ["diario", "Lo vas a usar cada día al hablar"],
    "M2-L5": ["diario", "Lo vas a usar cada día al hablar"],
    "M2-L6": ["diario", "Lo vas a usar cada día al hablar"],
    "M2-L7": ["diario", "Lo vas a usar cada día al hablar"],
    "M2-L8": ["diario", "Lo vas a usar cada día al hablar"],
    "M2-L9": ["diario", "Lo vas a usar cada día al hablar"],
    "M2-L10": ["diario", "Lo vas a usar cada día al hablar"],
    "M3-L1": ["diario", "Lo vas a usar cada día al hablar"],
    "M3-L2": ["diario", "Lo vas a usar cada día al hablar"],
    "M3-L3": ["formal", "Casi solo en textos escritos o formales"],
    "M3-L4": ["diario", "Lo vas a usar cada día al hablar"],
    "M3-L5": ["diario", "Lo vas a usar cada día al hablar"],
    "M3-L6": ["diario", "Lo vas a usar cada día al hablar"],
    "M3-L7": ["diario", "Lo vas a usar cada día al hablar"],
    "M3-L8": ["diario", "Lo vas a usar cada día al hablar"],
    "M3-L9": ["diario", "Lo vas a usar cada día al hablar"],
    "M3-L10": ["frecuente", "Se usa bastante en conversación"],
    "M4-L1": ["diario", "Lo vas a usar cada día al hablar"],
    "M4-L2": ["diario", "Lo vas a usar cada día al hablar"],
    "M4-L3": ["diario", "Lo vas a usar cada día al hablar"],
    "M4-L4": ["diario", "Lo vas a usar cada día al hablar"],
    "M4-L5": ["diario", "Lo vas a usar cada día al hablar"],
    "M4-L6": ["frecuente", "Se usa bastante en conversación"],
    "M4-L7": ["frecuente", "Se usa bastante en conversación"],
    "M4-L8": ["frecuente", "Se usa bastante en conversación"],
    "M4-L9": ["diario", "Lo vas a usar cada día al hablar"],
    "M4-L10": ["frecuente", "Se usa bastante en conversación"],
    "M5-L1": ["frecuente", "Se usa bastante en conversación"],
    "M5-L2": ["frecuente", "Se usa bastante en conversación"],
    "M5-L3": ["frecuente", "Se usa bastante en conversación"],
    "M5-L4": ["entender", "Sobre todo para entender lo que oyes y lees"],
    "M5-L5": ["frecuente", "Se usa bastante en conversación"],
    "M5-L6": ["frecuente", "Se usa bastante en conversación"],
    "M5-L7": ["frecuente", "Se usa bastante en conversación"],
    "M5-L8": ["frecuente", "Se usa bastante en conversación"],
    "M5-L9": ["entender", "Sobre todo para entender lo que oyes y lees"],
    "M5-L10": ["frecuente", "Se usa bastante en conversación"],
    "M6-L1": ["entender", "Sobre todo para entender lo que oyes y lees"],
    "M6-L2": ["entender", "Sobre todo para entender lo que oyes y lees"],
    "M6-L3": ["entender", "Sobre todo para entender lo que oyes y lees"],
    "M6-L4": ["frecuente", "Se usa bastante en conversación"],
    "M6-L5": ["entender", "Sobre todo para entender lo que oyes y lees"],
    "M6-L6": ["entender", "Sobre todo para entender lo que oyes y lees"],
    "M6-L7": ["entender", "Sobre todo para entender lo que oyes y lees"],
    "M6-L8": ["entender", "Sobre todo para entender lo que oyes y lees"],
    "M6-L9": ["entender", "Sobre todo para entender lo que oyes y lees"],
    "M6-L10": ["frecuente", "Se usa bastante en conversación"],
    "M7-L1": ["entender", "Sobre todo para entender lo que oyes y lees"],
    "M7-L2": ["entender", "Sobre todo para entender lo que oyes y lees"],
    "M7-L3": ["frecuente", "Se usa bastante en conversación"],
    "M7-L4": ["formal", "Casi solo en textos escritos o formales"],
    "M7-L5": ["entender", "Sobre todo para entender lo que oyes y lees"],
    "M7-L6": ["entender", "Sobre todo para entender lo que oyes y lees"],
    "M7-L7": ["formal", "Casi solo en textos escritos o formales"],
    "M7-L8": ["formal", "Casi solo en textos escritos o formales"],
    "M7-L9": ["entender", "Sobre todo para entender lo que oyes y lees"],
    "M7-L10": ["frecuente", "Se usa bastante en conversación"],
    "M8-L1": ["formal", "Casi solo en textos escritos o formales"],
    "M8-L2": ["formal", "Casi solo en textos escritos o formales"],
    "M8-L3": ["formal", "Casi solo en textos escritos o formales"],
    "M8-L4": ["entender", "Sobre todo para entender lo que oyes y lees"],
    "M8-L5": ["formal", "Casi solo en textos escritos o formales"],
    "M8-L6": ["formal", "Casi solo en textos escritos o formales"],
    "M8-L7": ["formal", "Casi solo en textos escritos o formales"],
    "M8-L8": ["formal", "Casi solo en textos escritos o formales"],
    "M8-L9": ["formal", "Casi solo en textos escritos o formales"],
    "M8-L10": ["frecuente", "Se usa bastante en conversación"],
    "M9-L1": ["entender", "Sobre todo para entender lo que oyes y lees"],
    "M9-L2": ["formal", "Casi solo en textos escritos o formales"],
    "M9-L3": ["entender", "Sobre todo para entender lo que oyes y lees"],
    "M9-L4": ["formal", "Casi solo en textos escritos o formales"],
    "M9-L5": ["formal", "Casi solo en textos escritos o formales"],
    "M9-L6": ["formal", "Casi solo en textos escritos o formales"],
    "M9-L7": ["entender", "Sobre todo para entender lo que oyes y lees"],
    "M9-L8": ["formal", "Casi solo en textos escritos o formales"],
    "M9-L9": ["formal", "Casi solo en textos escritos o formales"],
    "M9-L10": ["frecuente", "Se usa bastante en conversación"],
    "M10-L1": ["formal", "Casi solo en textos escritos o formales"],
    "M10-L2": ["formal", "Casi solo en textos escritos o formales"],
    "M10-L3": ["entender", "Sobre todo para entender lo que oyes y lees"],
    "M10-L4": ["formal", "Casi solo en textos escritos o formales"],
    "M10-L5": ["formal", "Casi solo en textos escritos o formales"],
    "M10-L6": ["formal", "Casi solo en textos escritos o formales"],
    "M10-L7": ["formal", "Casi solo en textos escritos o formales"],
    "M10-L8": ["formal", "Casi solo en textos escritos o formales"],
    "M10-L9": ["formal", "Casi solo en textos escritos o formales"],
    "M10-L10": ["formal", "Casi solo en textos escritos o formales"],
};

if (typeof window !== "undefined") {
    window.USO_REAL = USO_REAL;
}
