// Vocabulario por nivel. Las palabras se extrajeron de los ejercicios
// reales de cada nivel, asi que corresponden a su tema y a su nivel MCER.
const VOCABULARY_BANK = {
    "M1-L1": [["ciao", "hola"], ["chiedo", "pido"], ["caffè", "café"], ["entro", "entro"], ["bar", "bar"]],
    "M1-L2": [["tavolo", "mesa"], ["casa", "casa"], ["piccolo", "pequeño"], ["porta", "puerta"], ["aperta", "abierta"]],
    "M1-L3": [["anni", "años"], ["venti", "veinte"], ["ventidue", "veintidós"], ["spagnolo", "español"], ["spagnola", "española"], ["oggi", "hoy"], ["compra", "compra"], ["due", "dos"]],
    "M1-L4": [["mercato", "mercado"], ["lavora", "trabaja"], ["oggi", "hoy"], ["vai", "vas"], ["compro", "compro"], ["carne", "carne"]],
    "M1-L5": [["lavoro", "trabajo"], ["centro", "centro"], ["apriamo", "abrimos"], ["studi", "estudias"], ["casa", "casa"], ["negozio", "tienda"], ["otto", "ocho"]],
    "M1-L6": [["sorella", "hermana"], ["vive", "vive"], ["qui", "aquí"], ["amico", "amigo"], ["arriva", "llega"], ["madre", "madre"]],
    "M1-L7": [["sette", "siete"], ["alzo", "me levanto"], ["otto", "ocho"], ["bevo", "bebo"], ["caffè", "café"], ["poi", "luego"], ["lavoro", "trabajo"], ["vado", "voy"]],
    "M1-L8": [["lavoro", "trabajo"], ["libro", "libro"], ["tavolo", "mesa"], ["borsa", "bolso"], ["macchina", "coche"]],
    "M1-L9": [["vorrei", "querría"], ["panino", "bocadillo"], ["favore", "favor"], ["bar", "bar"], ["dice", "dice"], ["acqua", "agua"], ["caffè", "café"]],
    "M1-L10": [["arriva", "llega"], ["presto", "pronto"], ["ordina", "pide"], ["poi", "luego"], ["torna", "vuelve"], ["casa", "casa"], ["contento", "contento"], ["caffè", "café"], ["parla", "habla"]],
    "M2-L1": [["sorella", "hermana"], ["amico", "amigo"], ["fratello", "hermano"], ["nostra", "nuestra"], ["cugina", "prima"], ["madre", "madre"]],
    "M2-L2": [["cucina", "cocina"], ["due", "dos"], ["casa", "casa"], ["piccola", "pequeña"], ["camere", "habitaciones"], ["salotto", "salón"], ["divano", "sofá"], ["grande", "grande"], ["sedie", "sillas"], ["letto", "cama"]],
    "M2-L3": [["faccio", "hago"], ["colazione", "desayuno"], ["alzo", "me levanto"], ["sette", "siete"], ["comincio", "empiezo"], ["lavorare", "trabajar"], ["otto", "ocho"], ["mattina", "mañana"], ["calma", "calma"], ["prima", "antes"]],
    "M2-L4": [["posso", "puedo"], ["uscire", "salir"], ["voglio", "quiero"], ["oggi", "hoy"], ["chiamarti", "llamarte"], ["dopo", "después"], ["stasera", "esta noche"], ["studiare", "estudiar"], ["andare", "ir"]],
    "M2-L5": [["vorrei", "querría"], ["chilo", "kilo"], ["mezzo", "medio"], ["pomodori", "tomates"], ["formaggio", "queso"], ["mele", "manzanas"], ["pane", "pan"], ["due", "dos"], ["etti", "cien gramos"]],
    "M2-L6": [["ieri", "ayer"], ["comprato", "comprado"], ["libro", "libro"], ["studiato", "estudiado"], ["casa", "casa"], ["mangiato", "comido"], ["presto", "pronto"], ["guardato", "visto"], ["film", "película"], ["visitato", "visitado"]],
    "M2-L7": [["arrivato", "llegado"], ["tardi", "tarde"], ["tornato", "vuelto"], ["casa", "casa"], ["poi", "luego"], ["ieri", "ayer"], ["subito", "enseguida"], ["andato", "ido"], ["centro", "centro"], ["autobus", "autobús"]],
    "M2-L8": [["domani", "mañana"], ["sera", "tarde/noche"], ["cenare", "cenar"], ["fuori", "fuera"], ["andare", "ir"], ["cinema", "cine"], ["volentieri", "con gusto"]],
    "M2-L9": [["vai", "vas"], ["dritto", "recto"], ["gira", "gira"], ["sinistra", "izquierda"], ["stazione", "estación"], ["davanti", "delante"], ["poi", "luego"], ["banca", "banco"], ["accanto", "al lado"], ["museo", "museo"]],
    "M2-L10": [["ieri", "ayer"], ["andato", "ido"], ["mercato", "mercado"], ["comprato", "comprado"], ["frutta", "fruta"], ["poi", "luego"], ["cenato", "cenado"], ["sorella", "hermana"]],
    "M3-L1": [["vivevo", "vivía"], ["vicino", "cerca"], ["mare", "mar"], ["passavo", "pasaba"], ["pomeriggi", "tardes"], ["strada", "calle"], ["bambino", "niño"], ["amici", "amigos"], ["piccolo", "pequeño"]],
    "M3-L2": [["mentre", "mientras"], ["studiavo", "estudiaba"], ["arrivato", "llegado"], ["messaggio", "mensaje"], ["cambiato", "cambiado"]],
    "M3-L3": [["caldaia", "caldera"], ["funzionava", "funcionaba"], ["bene", "bien"], ["così", "así"], ["chiamato", "llamado"]],
    "M3-L4": [["male", "mal"], ["due", "dos"], ["giorni", "días"], ["sto", "estoy"], ["gola", "garganta"], ["bevo", "bebo"], ["solo", "solo"], ["caldo", "calor"]],
    "M3-L5": [["più", "más"], ["meno", "menos"], ["vicino", "cerca"], ["mercato", "mercado"], ["casa", "casa"], ["negozio", "tienda"], ["caffè", "café"], ["buono", "bueno"]],
    "M3-L6": [["studio", "estudio"], ["sera", "tarde/noche"], ["lavoro", "trabajo"], ["giorno", "día"], ["quindi", "por tanto"], ["organizzo", "organizo"], ["attenzione", "atención"], ["bene", "bien"]],
    "M3-L7": [["prenotato", "reservado"], ["treno", "tren"], ["notturno", "nocturno"], ["partiti", "salidos"], ["due", "dos"], ["valigie", "maletas"], ["leggere", "leer"]],
    "M3-L8": [["ieri", "ayer"], ["visto", "visto"], ["consigliato", "aconsejado"], ["letto", "cama"], ["film", "película"], ["libro", "libro"]],
    "M3-L9": [["porto", "llevo"], ["copia", "copia"], ["domani", "mañana"], ["piace", "gusta"], ["libro", "libro"], ["quindi", "por tanto"]],
    "M3-L10": [["mentre", "mientras"], ["tornavamo", "volvíamos"], ["casa", "casa"], ["chiamati", "llamados"], ["raccontato", "contado"], ["notizia", "noticia"], ["inattesa", "inesperada"]],
    "M4-L1": [["prendi", "coge"], ["biglietto", "billete"], ["aspetta", "espera"], ["qui", "aquí"], ["poi", "luego"], ["seguimi", "sígueme"], ["fino", "hasta"], ["fermata", "parada"]],
    "M4-L2": [["scusi", "perdone"], ["potrebbe", "podría"], ["aiutarmi", "ayudarme"], ["vorrei", "querría"], ["sapere", "saber"], ["postale", "postal"]],
    "M4-L3": [["devo", "debo"], ["riposare", "descansar"], ["medico", "médico"], ["dice", "dice"], ["lavorare", "trabajar"], ["due", "dos"], ["giorni", "días"], ["deve", "debe"], ["bere", "beber"], ["acqua", "agua"]],
    "M4-L4": [["camera", "habitación"], ["rumore", "ruido"], ["funzionava", "funcionaba"], ["così", "así"], ["chiesto", "pedido"], ["cambio", "cambio"]],
    "M4-L5": [["tre", "tres"], ["più", "más"], ["ristoranti", "restaurantes"], ["tranquillo", "tranquilo"], ["meno", "menos"], ["caro", "caro"], ["comodo", "cómodo"]],
    "M4-L6": [["vado", "voy"], ["parlo", "hablo"], ["vai", "vas"], ["spesso", "a menudo"], ["museo", "museo"], ["ogni", "cada"], ["mese", "mes"], ["sempre", "siempre"], ["volentieri", "con gusto"]],
    "M4-L7": [["mando", "envío"], ["subito", "enseguida"], ["vuoi", "quieres"], ["documento", "documento"], ["spiego", "explico"], ["contenuto", "contenido"]],
    "M4-L8": [["anno", "año"], ["lavorero", "trabajaré"], ["milano", "Milán"], ["vivro", "viviré"], ["vicino", "cerca"], ["parco", "parque"], ["centrale", "central"], ["domani", "mañana"], ["parlero", "hablaré"], ["direttore", "director"]],
    "M4-L9": [["vorrei", "querría"], ["cambiare", "cambiar"], ["tavolo", "mesa"], ["possibile", "posible"], ["potrei", "podría"], ["pagare", "pagar"], ["carta", "tarjeta"]],
    "M4-L10": [["reception", "recepción"], ["spiegato", "explicado"], ["problema", "problema"], ["risolto", "resuelto"], ["fine", "final"], ["uscito", "salido"], ["soddisfatto", "satisfecho"]],
    "M5-L1": [["libro", "libro"], ["leggo", "leo"], ["parla", "habla"], ["città", "ciudad"], ["nessuno", "nadie"], ["dorme", "duerme"], ["presto", "pronto"]],
    "M5-L2": [["secondo", "según"], ["quartiere", "barrio"], ["cambiando", "cambiando"], ["penso", "pienso"], ["presto", "pronto"], ["diventera", "se volverá"], ["più", "más"], ["vivo", "vivo"]],
    "M5-L3": [["progetto", "proyecto"], ["costa", "cuesta"], ["tuttavia", "sin embargo"], ["può", "puede"], ["migliorare", "mejorar"], ["quartiere", "barrio"], ["inoltre", "además"], ["creare", "crear"], ["lavoro", "trabajo"]],
    "M5-L4": [["città", "ciudad"], ["mangia", "come"], ["tardi", "tarde"], ["parla", "habla"], ["strada", "calle"]],
    "M5-L5": [["finisco", "termino"], ["presto", "pronto"], ["usciremo", "saldremos"], ["insieme", "juntos"], ["vedremo", "veremos"], ["nuovo", "nuevo"], ["museo", "museo"]],
    "M5-L6": [["detto", "dicho"], ["arrivava", "llegaba"], ["tardi", "tarde"], ["poi", "luego"], ["avrebbe", "habría"], ["chiamati", "llamados"]],
    "M5-L7": [["documento", "documento"], ["parlano", "hablan"], ["contiene", "contiene"], ["utili", "útiles"]],
    "M5-L8": [["arrivato", "llegado"], ["italia", "Italia"], ["capivo", "entendía"], ["ogni", "cada"], ["giorno", "día"], ["parlavo", "hablaba"], ["più", "más"], ["sicurezza", "seguridad"]],
    "M5-L9": [["penso", "pienso"], ["sia", "sea"], ["buona", "buena"], ["idea", "idea"], ["spero", "espero"], ["capiscano", "entiendan"], ["progetto", "proyecto"]],
    "M5-L10": [["quartiere", "barrio"], ["cambiera", "cambiará"], ["davvero", "de verdad"], ["penso", "pienso"], ["molti", "muchos"], ["giovani", "jóvenes"], ["troveranno", "encontrarán"], ["nuove", "nuevas"], ["opportunità", "oportunidades"], ["sarà", "será"]],
    "M6-L1": [["credo", "creo"], ["direttore", "director"], ["sappia", "sepa"], ["temo", "temo"], ["capisca", "entienda"], ["problema", "problema"]],
    "M6-L2": [["penso", "pienso"], ["abbia", "haya"], ["scelto", "elegido"], ["bene", "bien"], ["anche", "también"], ["nessuno", "nadie"], ["detto", "dicho"], ["apertamente", "abiertamente"]],
    "M6-L3": [["stato", "sido"], ["progetto", "proyecto"], ["approvato", "aprobado"], ["ieri", "ayer"], ["presentato", "presentado"]],
    "M6-L4": [["sto", "estoy"], ["leggendo", "leyendo"], ["rapporto", "informe"], ["camminando", "caminando"], ["lentamente", "lentamente"], ["verso", "hacia"], ["stazione", "estación"]],
    "M6-L5": [["avessi", "tuviera"], ["più", "más"], ["tempo", "tiempo"], ["seguirei", "seguiría"], ["corso", "curso"], ["serale", "nocturno"], ["cucina", "cocina"], ["italiana", "italiana"]],
    "M6-L6": [["piova", "llueva"], ["mercato", "mercado"], ["resta", "queda"], ["pieno", "lleno"], ["continuano", "continúan"], ["discutere", "discutir"]],
    "M6-L7": [["spiegato", "explicado"], ["sistema", "sistema"], ["avrebbe", "habría"], ["richiesto", "solicitado"], ["aggiornamento", "actualización"], ["urgente", "urgente"]],
    "M6-L8": [["visto", "visto"], ["ragazzi", "chicos"], ["entrare", "entrar"], ["silenzio", "silencio"], ["uscire", "salir"], ["più", "más"], ["tranquilli", "tranquilos"]],
    "M6-L9": [["breve", "breve"], ["piano", "plan/piso"], ["riduce", "reduce"], ["costi", "costes"], ["migliora", "mejora"], ["servizi", "servicios"], ["rafforza", "refuerza"], ["rete", "red"], ["locale", "local"]],
    "M6-L10": [["stato", "sido"], ["piano", "plan/piso"], ["fosse", "fuera"], ["discusso", "discutido"], ["prima", "antes"], ["credo", "creo"], ["sarebbe", "sería"], ["accolto", "acogido"], ["meglio", "mejor"]],
    "M7-L1": [["contratto", "contrato"], ["era", "era"], ["pronto", "listo"], ["inviato", "enviado"], ["appena", "apenas"], ["ricevuto", "recibido"], ["corretto", "correcto"]],
    "M7-L2": [["quartiere", "barrio"], ["conosco", "conozco"], ["bene", "bien"], ["lavorato", "trabajado"], ["anni", "años"]],
    "M7-L3": [["budget", "presupuesto"], ["era", "era"], ["ciononostante", "aun así"], ["lavoro", "trabajo"], ["tempi", "tiempos"]],
    "M7-L4": [["ieri", "ayer"], ["più", "más"]],
    "M7-L5": [["problema", "problema"], ["parlato", "hablado"], ["ancora", "todavía"], ["due", "dos"]],
    "M7-L6": [["chiarire", "aclarar"]],
    "M7-L7": [["segnalare", "señalar"], ["entro", "entro"]],
    "M7-L8": [["servizio", "servicio"], ["ogni", "cada"]],
    "M7-L10": [["parlato", "hablado"], ["ciononostante", "aun así"], ["dato", "dato"]],
    "M8-L1": [["piano", "plan/piso"], ["riduce", "reduce"], ["costi", "costes"], ["più", "más"]],
    "M8-L2": [["tempi", "tiempos"], ["servizio", "servicio"]],
    "M8-L3": [["ancora", "todavía"], ["accessibile", "accesible"]],
    "M8-L4": [["molti", "muchos"], ["continuano", "continúan"], ["segnalare", "señalar"], ["criticità", "punto crítico"]],
    "M8-L5": [["rapporto", "informe"], ["tre", "tres"]],
    "M8-L6": [["secondo", "según"], ["primo", "primero"], ["studio", "estudio"], ["quartiere", "barrio"]],
    "M8-L7": [["dato", "dato"], ["potrebbe", "podría"]],
    "M8-L8": [["primo", "primero"], ["problema", "problema"], ["secondo", "según"]],
    "M8-L9": [["tuttavia", "sin embargo"], ["può", "puede"]],
    "M8-L10": [["contesto", "contexto"]],
    "M9-L1": [["fine", "final"], ["bene", "bien"]],
    "M9-L2": [["fosse", "fuera"], ["possibile", "posible"]],
    "M9-L3": [["idea", "idea"], ["senza", "sin"]],
    "M9-L4": [["città", "ciudad"], ["prima", "antes"]],
    "M9-L5": [["problema", "problema"], ["solo", "solo"], ["anche", "también"]],
    "M9-L6": [["amici", "amigos"], ["criticità", "punto crítico"]],
    "M9-L7": [["mercato", "mercado"], ["riesco", "consigo"]],
    "M9-L8": [["spiego", "explico"], ["problema", "problema"], ["più", "más"]],
    "M9-L9": [["testo", "texto"], ["più", "más"], ["chiarire", "aclarar"]],
    "M9-L10": [["riesco", "consigo"]],
    "M10-L1": [["testo", "texto"], ["accessibile", "accesible"], ["senza", "sin"]],
    "M10-L2": [["portata", "alcance"], ["poi", "luego"]],
    "M10-L3": [["cambiando", "cambiando"], ["contenuto", "contenido"]],
    "M10-L4": [["contesto", "contexto"]],
    "M10-L5": [["chiarire", "aclarar"], ["servizio", "servicio"]],
    "M10-L6": [["senza", "sin"]],
    "M10-L7": [["riduce", "reduce"], ["portata", "alcance"], ["lessicale", "léxico"]],
    "M10-L8": [["parlo", "hablo"], ["senza", "sin"], ["organizzo", "organizo"], ["tempo", "tiempo"], ["mentre", "mientras"]],
    "M10-L9": [["più", "más"], ["testo", "texto"], ["senza", "sin"]],
    "M10-L10": [["lessicale", "léxico"]],
};

if (typeof window !== "undefined") {
    window.VOCABULARY_BANK = VOCABULARY_BANK;
}
